apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<account_id>:role/<eks-node-role>
      username: system:node:{{SessionName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::653470767467:user/Ankushk-ops
      username: github-actions
      groups:
        - system:masters
