name: ECR

# on:
#   workflow_dispatch:
#     inputs:
#       image_tag:
#         description: "Tag for the Docker image"
#         required: true
#         default: "latest"
on:
  push:
    branches:
      - main

env:
  REGION: eu-north-1 
  ECR_REPOSITORY: 653470767467.dkr.ecr.eu-north-1.amazonaws.com/nakul-github-repo
 # IMAGE_NAME: 

jobs:
  build-and-scan:
    name: Build and Scan Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build Docker Image
      id: build-docker
      run: |
        IMAGE_URI="${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
        docker build -t "$IMAGE_URI" .
        echo "::set-output name=image_uri::$IMAGE_URI"

    - name: Scan Docker Image
      id: trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.build-docker.outputs.image_uri }}
        format: table
        exit-code: 0 
      continue-on-error: true

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push Docker Image to ECR
      if: success() # Only push if the scan passes
      run: |
        IMAGE_URI="${{ steps.build-docker.outputs.image_uri }}"
        echo "Pushing Docker Image $IMAGE_URI to Amazon ECR..."
        docker push "$IMAGE_URI"
