name: Build Docker Image and Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan-and-build:
    name: Snyk Code Scan and Docker Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history for better analysis

      # Step 2: Set up Node.js environment for Snyk dependency scan
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install  # Install any dependencies listed in package.json

      # Step 3: Snyk dependency security scan
      - name: Snyk Dependency Scan
        uses: snyk/actions/node@master
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 5: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t my-dockerhub-user/my-app:${{ github.sha }} .
          docker tag my-dockerhub-user/my-app:${{ github.sha }} my-dockerhub-user/my-app:latest

      # Step 6: Snyk Docker Image Scan
      - name: Snyk Docker Image Scan
        uses: snyk/actions/docker@master
        with:
          image: my-dockerhub-user/my-app:${{ github.sha }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Step 7: Push Docker Image to Registry
      - name: Push Docker Image to Registry
        run: |
          docker push my-dockerhub-user/my-app:${{ github.sha }}
          docker push my-dockerhub-user/my-app:latest
